[package]
name = "plrust-lib-example"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pgrx/pg16"]
pg_test = []
trusted = []

[dependencies]
pgrx = "=0.11.0"

[dev-dependencies]
pgrx-tests = "=0.11.0"
